//! Recompiled GameCube game functions — PLACEHOLDER.
//!
//! The real contents of this file are generated by `gcrecomp recompile`
//! (the whole game is ~14k functions / >80MB of Rust, so it is NOT committed).
//! Run, from the workspace root:
//!
//! ```text
//! cargo run -p gcrecomp-cli -- recompile --dol-file <game.dol>
//! ```
//!
//! That overwrites this file with the recompiled game, then `cargo build -p game`
//! links it. This placeholder lets the workspace compile from a fresh checkout.
#![allow(warnings, clippy::all, clippy::pedantic, clippy::nursery)]

use anyhow::Result;
use gcrecomp_core::runtime::context::CpuContext;
use gcrecomp_core::runtime::memory::MemoryManager;

/// Original DOL entry-point address. Overwritten by the generator.
pub const ENTRY_POINT: u32 = 0;

/// Dispatch a recompiled function by address. The placeholder knows none.
pub fn call_function_by_address(
    _address: u32,
    _ctx: &mut CpuContext,
    _memory: &mut MemoryManager,
) -> Result<Option<u32>> {
    Ok(None)
}
