//! Recompiled GameCube game functions — PLACEHOLDER.
//!
//! The real contents are generated by `gcrecomp recompile` (the whole game is
//! ~14k functions / millions of lines + a multi-MB memory image, so they are NOT
//! committed). From the workspace root:
//!
//! ```text
//! ./play.sh <game.dol>                 # recompile + build + run
//! # or: cargo run -p gcrecomp-cli -- recompile --dol-file <game.dol>
//! ```
//!
//! This placeholder lets the workspace compile from a fresh checkout.
#![allow(warnings, clippy::all, clippy::pedantic, clippy::nursery)]

use anyhow::Result;
use gcrecomp_core::runtime::context::CpuContext;
use gcrecomp_core::runtime::memory::MemoryManager;

/// Original DOL entry-point address. Overwritten by the generator.
pub const ENTRY_POINT: u32 = 0;

/// Load the DOL memory image into RAM. The placeholder has no image.
pub fn load_image(_memory: &mut MemoryManager) {}

/// Dispatch a recompiled function by address. The placeholder knows none.
pub fn call_function_by_address(
    _address: u32,
    _ctx: &mut CpuContext,
    _memory: &mut MemoryManager,
) -> Result<Option<u32>> {
    Ok(None)
}
