// Game entry point — full game runtime
#[allow(dead_code)]
mod assets;
// The recompiled game code is its own crate `recompiled` (generated by
// `gcrecomp recompile`); referenced directly as `recompiled::...`.

use anyhow::Result;
use gcrecomp_core::runtime::context::CpuContext;
use gcrecomp_core::runtime::memory::MemoryManager;
use gcrecomp_core::runtime::sdk::os::OsState;
use log::info;
use std::sync::Arc;
use winit::application::ApplicationHandler;
use winit::event::{KeyEvent, WindowEvent};
use winit::event_loop::{ControlFlow, EventLoop};
use winit::keyboard::{Key, NamedKey};
use winit::window::Window;

struct GameApp {
    window: Option<Arc<Window>>,
    runtime: Option<gcrecomp_runtime::runtime::Runtime>,
    /// The recompiled execution's RAM, persisted so the renderer can read the XFB.
    memory: MemoryManager,
    menu_visible: bool,
    /// External framebuffer (XFB) location/size to present, configurable via env.
    xfb_addr: u32,
    xfb_w: u32,
    xfb_h: u32,
}

impl GameApp {
    fn new() -> Self {
        let mut memory = MemoryManager::new();
        let mut os_state = OsState::new();
        let mut ctx = CpuContext::new();

        // SDK init + DVD filesystem + load the DOL's real memory image into RAM.
        gcrecomp_core::runtime::sdk::os::os_init(&mut os_state, &mut memory);
        os_state.init_dvd(assets::ARCHIVE);
        recompiled::load_image(&mut memory);

        ctx.set_register(1, 0x817F_FF00); // r1 = stack pointer (top of MEM1)
        ctx.set_register(2, 0x8040_0000); // SDA2 base
        ctx.set_register(13, 0x8040_0000); // SDA base

        // Run the recompiled entry once; its writes to RAM persist in `memory`,
        // which the render loop then presents as the framebuffer.
        let entry = recompiled::ENTRY_POINT;
        info!("Running recompiled entry point 0x{:08X}...", entry);
        // Give the recompiled boot code a few seconds, then stop it (it spins on
        // hardware we don't fully emulate). The window then shows the resulting XFB.
        gcrecomp_core::runtime::arm_watchdog(5);
        let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            recompiled::call_function_by_address(entry, &mut ctx, &mut memory)
        }));
        match r {
            Ok(Ok(v)) => info!("Recompiled entry 0x{:08X} returned {:?}", entry, v),
            Ok(Err(e)) => log::warn!("Recompiled entry 0x{:08X} error: {e}", entry),
            Err(_) => log::warn!("Recompiled entry 0x{:08X} panicked (contained)", entry),
        }

        let env_u32 = |k: &str, d: u32| {
            std::env::var(k)
                .ok()
                .and_then(|s| parse_u32(&s))
                .unwrap_or(d)
        };

        // Did the recompiled boot program the VI framebuffer register (VI_TFBL,
        // 0xCC00201C)? If so, that's the real XFB address. The register stores the
        // physical address >> 5 in its low 24 bits.
        let vi_xfb = memory
            .read_u32(0xCC00_201C)
            .ok()
            .filter(|&v| v != 0)
            .map(|tfbl| {
                let xfb = 0x8000_0000 | ((tfbl & 0x00FF_FFFF) << 5);
                info!("VI_TFBL=0x{tfbl:08X} -> using XFB at 0x{xfb:08X}");
                xfb
            });
        if vi_xfb.is_none() {
            info!("VI framebuffer register not programmed by boot; using default/env XFB");
        }
        // Priority: explicit env override > VI register > start of MEM1.
        let xfb_addr = std::env::var("GCRECOMP_XFB")
            .ok()
            .and_then(|s| parse_u32(&s))
            .or(vi_xfb)
            .unwrap_or(0x8000_0000);

        Self {
            window: None,
            runtime: None,
            memory,
            menu_visible: false,
            xfb_addr,
            xfb_w: env_u32("GCRECOMP_XFB_W", 640),
            xfb_h: env_u32("GCRECOMP_XFB_H", 480),
        }
    }
}

/// Parse a u32 from decimal or `0x`-prefixed hex.
fn parse_u32(s: &str) -> Option<u32> {
    let s = s.trim();
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16).ok()
    } else {
        s.parse().ok()
    }
}

/// BT.601 YUV (0-255) -> RGB (0-255).
fn yuv_to_rgb(y: u8, cb: u8, cr: u8) -> [u8; 3] {
    let y = y as f32;
    let cb = cb as f32 - 128.0;
    let cr = cr as f32 - 128.0;
    let clamp = |v: f32| v.clamp(0.0, 255.0) as u8;
    [
        clamp(y + 1.402 * cr),
        clamp(y - 0.344 * cb - 0.714 * cr),
        clamp(y + 1.772 * cb),
    ]
}

/// Read a GameCube XFB (YUYV 4:2:2) from emulated RAM into RGBA8.
fn read_xfb_rgba(memory: &MemoryManager, addr: u32, w: u32, h: u32) -> Vec<u8> {
    let mut out = vec![0u8; (w as usize) * (h as usize) * 4];
    for y in 0..h {
        for x2 in 0..(w / 2) {
            // 4 bytes (Y0, Cb, Y1, Cr) per 2 horizontal pixels.
            let off = addr.wrapping_add((y * w + x2 * 2) * 2);
            let word = memory.read_u32(off).unwrap_or(0);
            let y0 = (word >> 24) as u8;
            let cb = (word >> 16) as u8;
            let y1 = (word >> 8) as u8;
            let cr = word as u8;
            let p0 = yuv_to_rgb(y0, cb, cr);
            let p1 = yuv_to_rgb(y1, cb, cr);
            let base = ((y * w + x2 * 2) * 4) as usize;
            out[base..base + 3].copy_from_slice(&p0);
            out[base + 3] = 255;
            out[base + 4..base + 7].copy_from_slice(&p1);
            out[base + 7] = 255;
        }
    }
    out
}

impl ApplicationHandler for GameApp {
    fn resumed(&mut self, event_loop: &winit::event_loop::ActiveEventLoop) {
        if self.window.is_some() {
            return;
        }

        let attrs = Window::default_attributes()
            .with_title("GCRecomp")
            .with_inner_size(winit::dpi::LogicalSize::new(1280, 720));

        // Headless-safe: a missing display or GPU must not crash the process.
        let window = match event_loop.create_window(attrs) {
            Ok(w) => Arc::new(w),
            Err(e) => {
                log::warn!("No window ({e}); exiting event loop (headless).");
                event_loop.exit();
                return;
            }
        };

        let mut runtime = match gcrecomp_runtime::runtime::Runtime::new() {
            Ok(r) => r,
            Err(e) => {
                log::warn!("Runtime init failed ({e}); exiting event loop.");
                event_loop.exit();
                return;
            }
        };

        // wgpu can panic (not just Err) when there's no usable adapter, so contain it.
        let gfx = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            runtime.initialize_graphics(window.clone())
        }));
        match gfx {
            Ok(Ok(())) => {}
            Ok(Err(e)) => log::warn!("Graphics init failed ({e}); running without rendering."),
            Err(_) => log::warn!("Graphics init panicked (no GPU?); running without rendering."),
        }
        if let Err(e) = runtime.initialize_audio() {
            log::warn!("Audio init failed (continuing without audio): {e}");
        }
        info!("Runtime initialized");

        self.window = Some(window);
        self.runtime = Some(runtime);
    }

    fn window_event(
        &mut self,
        event_loop: &winit::event_loop::ActiveEventLoop,
        _window_id: winit::window::WindowId,
        event: WindowEvent,
    ) {
        let runtime = match self.runtime.as_mut() {
            Some(r) => r,
            None => return,
        };

        match event {
            WindowEvent::CloseRequested => {
                info!("Window close requested");
                event_loop.exit();
            }
            WindowEvent::Resized(size) => {
                if let Some(renderer) = runtime.renderer_mut() {
                    renderer.resize(size.width, size.height);
                }
            }
            WindowEvent::KeyboardInput {
                event:
                    KeyEvent {
                        logical_key: Key::Named(NamedKey::Escape),
                        state: winit::event::ElementState::Pressed,
                        ..
                    },
                ..
            } => {
                self.menu_visible = !self.menu_visible;
                info!("Menu toggle: {}", self.menu_visible);
            }
            WindowEvent::RedrawRequested => {
                // Present the emulated external framebuffer (XFB) read from RAM.
                let (addr, w, h) = (self.xfb_addr, self.xfb_w, self.xfb_h);
                let rgba = read_xfb_rgba(&self.memory, addr, w, h);
                if let Some(renderer) = runtime.renderer_mut() {
                    if let Err(e) = renderer.present_framebuffer(&rgba, w, h) {
                        log::warn!("Present error: {e}");
                    }
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &winit::event_loop::ActiveEventLoop) {
        if let Some(runtime) = self.runtime.as_mut() {
            if let Err(e) = runtime.update() {
                log::warn!("Runtime update error: {}", e);
            }
        }
        if let Some(window) = &self.window {
            window.request_redraw();
        }
    }
}

fn main() -> Result<()> {
    // 1. Init logging
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    info!("GCRecomp game runtime starting");

    // 2. Init Lua engine and load UI screens
    let lua_engine = gcrecomp_lua::engine::LuaEngine::new()?;
    info!("Lua scripting engine initialized");

    // Load UI screen definitions
    let ui_init = std::path::Path::new("lua/ui/init.lua");
    if ui_init.exists() {
        if let Err(e) = lua_engine.execute_file(ui_init) {
            log::warn!("Failed to load UI screens: {}", e);
        }
    }

    // Load game initialization scripts
    let game_init = std::path::Path::new("lua/game/init.lua");
    if game_init.exists() {
        if let Err(e) = lua_engine.execute_file(game_init) {
            log::warn!("Failed to load game scripts: {}", e);
        }
    }

    // 3. Create the event loop and run. GameApp::new() runs the recompiled entry
    //    (persisting its RAM), and the render loop presents that RAM as the XFB.
    //    On a headless system there's no display, so exit cleanly.
    let event_loop = match EventLoop::new() {
        Ok(el) => el,
        Err(e) => {
            log::warn!("No display ({e}); running recompiled entry headless then exiting.");
            let _ = GameApp::new();
            return Ok(());
        }
    };
    event_loop.set_control_flow(ControlFlow::Poll);

    let mut app = GameApp::new();
    if let Err(e) = event_loop.run_app(&mut app) {
        log::warn!("Event loop ended: {e}");
    }

    Ok(())
}
