// Game entry point — full game runtime
#[allow(dead_code)]
mod assets;
// The recompiled game code is its own crate `recompiled` (generated by
// `gcrecomp recompile`); referenced directly as `recompiled::...`.

use anyhow::Result;
use gcrecomp_core::runtime::context::CpuContext;
use gcrecomp_core::runtime::memory::MemoryManager;
use gcrecomp_core::runtime::sdk::os::OsState;
use log::info;
use std::sync::Arc;
use winit::application::ApplicationHandler;
use winit::event::{KeyEvent, WindowEvent};
use winit::event_loop::{ControlFlow, EventLoop};
use winit::keyboard::{Key, NamedKey};
use winit::window::Window;

struct GameApp {
    window: Option<Arc<Window>>,
    runtime: Option<gcrecomp_runtime::runtime::Runtime>,
    _memory: MemoryManager,
    _os_state: OsState,
    _ctx: CpuContext,
    menu_visible: bool,
}

impl GameApp {
    fn new() -> Self {
        let mut memory = MemoryManager::new();
        let mut os_state = OsState::new();
        let mut ctx = CpuContext::new();

        // Run SDK init sequence
        gcrecomp_core::runtime::sdk::os::os_init(&mut os_state, &mut memory);

        // Initialize DVD virtual filesystem from embedded assets
        os_state.init_dvd(assets::ARCHIVE);

        // Setup initial CPU context
        ctx.set_register(1, 0x817F_FF00); // r1 = stack pointer (top of MEM1)
        ctx.set_register(13, 0x8040_0000); // Typical SDA base
        ctx.set_register(2, 0x8040_0000); // Typical SDA2 base

        info!("SDK initialized, CPU context ready");

        Self {
            window: None,
            runtime: None,
            _memory: memory,
            _os_state: os_state,
            _ctx: ctx,
            menu_visible: false,
        }
    }
}

impl ApplicationHandler for GameApp {
    fn resumed(&mut self, event_loop: &winit::event_loop::ActiveEventLoop) {
        if self.window.is_some() {
            return;
        }

        let attrs = Window::default_attributes()
            .with_title("GCRecomp")
            .with_inner_size(winit::dpi::LogicalSize::new(1280, 720));

        // Headless-safe: a missing display or GPU must not crash the process.
        let window = match event_loop.create_window(attrs) {
            Ok(w) => Arc::new(w),
            Err(e) => {
                log::warn!("No window ({e}); exiting event loop (headless).");
                event_loop.exit();
                return;
            }
        };

        let mut runtime = match gcrecomp_runtime::runtime::Runtime::new() {
            Ok(r) => r,
            Err(e) => {
                log::warn!("Runtime init failed ({e}); exiting event loop.");
                event_loop.exit();
                return;
            }
        };

        // wgpu can panic (not just Err) when there's no usable adapter, so contain it.
        let gfx = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            runtime.initialize_graphics(window.clone())
        }));
        match gfx {
            Ok(Ok(())) => {}
            Ok(Err(e)) => log::warn!("Graphics init failed ({e}); running without rendering."),
            Err(_) => log::warn!("Graphics init panicked (no GPU?); running without rendering."),
        }
        if let Err(e) = runtime.initialize_audio() {
            log::warn!("Audio init failed (continuing without audio): {e}");
        }
        info!("Runtime initialized");

        self.window = Some(window);
        self.runtime = Some(runtime);
    }

    fn window_event(
        &mut self,
        event_loop: &winit::event_loop::ActiveEventLoop,
        _window_id: winit::window::WindowId,
        event: WindowEvent,
    ) {
        let runtime = match self.runtime.as_mut() {
            Some(r) => r,
            None => return,
        };

        match event {
            WindowEvent::CloseRequested => {
                info!("Window close requested");
                event_loop.exit();
            }
            WindowEvent::Resized(size) => {
                if let Some(renderer) = runtime.renderer_mut() {
                    renderer.resize(size.width, size.height);
                }
            }
            WindowEvent::KeyboardInput {
                event:
                    KeyEvent {
                        logical_key: Key::Named(NamedKey::Escape),
                        state: winit::event::ElementState::Pressed,
                        ..
                    },
                ..
            } => {
                self.menu_visible = !self.menu_visible;
                info!("Menu toggle: {}", self.menu_visible);
            }
            WindowEvent::RedrawRequested => {
                if let Some(renderer) = runtime.renderer_mut() {
                    match renderer.begin_frame() {
                        Ok(frame) => {
                            renderer.end_frame(frame);
                        }
                        Err(e) => {
                            log::warn!("Frame error: {}", e);
                        }
                    }
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &winit::event_loop::ActiveEventLoop) {
        if let Some(runtime) = self.runtime.as_mut() {
            if let Err(e) = runtime.update() {
                log::warn!("Runtime update error: {}", e);
            }
        }
        if let Some(window) = &self.window {
            window.request_redraw();
        }
    }
}

fn main() -> Result<()> {
    // 1. Init logging
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    info!("GCRecomp game runtime starting");

    // 2. Init Lua engine and load UI screens
    let lua_engine = gcrecomp_lua::engine::LuaEngine::new()?;
    info!("Lua scripting engine initialized");

    // Load UI screen definitions
    let ui_init = std::path::Path::new("lua/ui/init.lua");
    if ui_init.exists() {
        if let Err(e) = lua_engine.execute_file(ui_init) {
            log::warn!("Failed to load UI screens: {}", e);
        }
    }

    // Load game initialization scripts
    let game_init = std::path::Path::new("lua/game/init.lua");
    if game_init.exists() {
        if let Err(e) = lua_engine.execute_file(game_init) {
            log::warn!("Failed to load game scripts: {}", e);
        }
    }

    // 3. Execute the recompiled entry point once (end-to-end: the generated game
    //    code actually runs). Contained in catch_unwind so a fault in the recompiled
    //    code logs and continues instead of taking down the host.
    run_recompiled_entry();

    // 4. Create event loop and run the windowed runtime. On a headless system
    //    (no display server) there's nothing to open a window on — the recompiled
    //    code has already run, so exit cleanly rather than erroring.
    let event_loop = match EventLoop::new() {
        Ok(el) => el,
        Err(e) => {
            log::warn!("No display ({e}); recompiled entry ran, exiting cleanly (headless).");
            return Ok(());
        }
    };
    event_loop.set_control_flow(ControlFlow::Poll);

    let mut app = GameApp::new();
    if let Err(e) = event_loop.run_app(&mut app) {
        log::warn!("Event loop ended: {e}");
    }

    Ok(())
}

/// Invoke the recompiled DOL entry point through the generated dispatcher.
/// This is the end-to-end link: parsed DOL -> recompiled Rust -> executed here.
fn run_recompiled_entry() {
    let mut memory = MemoryManager::new();
    let mut os_state = OsState::new();
    let mut ctx = CpuContext::new();

    gcrecomp_core::runtime::sdk::os::os_init(&mut os_state, &mut memory);
    ctx.set_register(1, 0x817F_FF00); // r1 = stack pointer (top of MEM1)
    ctx.set_register(2, 0x8040_0000); // SDA2 base
    ctx.set_register(13, 0x8040_0000); // SDA base

    let entry = recompiled::ENTRY_POINT;
    info!("Running recompiled entry point 0x{:08X}...", entry);

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        recompiled::call_function_by_address(entry, &mut ctx, &mut memory)
    }));

    match result {
        Ok(Ok(ret)) => info!("Recompiled entry 0x{:08X} returned {:?}", entry, ret),
        Ok(Err(e)) => log::warn!("Recompiled entry 0x{:08X} returned error: {}", entry, e),
        Err(_) => log::warn!("Recompiled entry 0x{:08X} panicked (contained)", entry),
    }
}
