//! Recompiled GameCube game functions
//! Generated by GCRecomp

use gcrecomp_core::runtime::context::CpuContext;
use gcrecomp_core::runtime::memory::MemoryManager;
use anyhow::Result;


pub fn call_function_by_address(
    _address: u32,
    _ctx: &mut CpuContext,
    _memory: &mut MemoryManager,
) -> Result<Option<u32>> {
    Ok(None)
}
